name: dinov2-extras
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.9
  - pytorch::pytorch=2.3.1
  - pytorch::pytorch-cuda=12.1
  - pytorch::torchvision=0.18.1
  - omegaconf
  - torchmetrics=0.10.3
  - fvcore
  - iopath
  - pip
  - pip:
    - git+https://github.com/facebookincubator/submitit
    - --extra-index-url https://pypi.nvidia.com
    - cuml-cu12
    - mmcv-full==1.5.0
    - mmsegmentation==0.27.0
